#!/bin/bash

case $1 in
    "--percentage")
        # Get battery percentage
        cat /sys/class/power_supply/BAT1/capacity 2>/dev/null || echo "100"
        ;;
    "--status")
        # Get battery status
        cat /sys/class/power_supply/BAT1/status 2>/dev/null || echo "Full"
        ;;
esac
