#!/bin/bash

BAT_PATH=$(find /sys/class/power_supply/ -maxdepth 1 -name "BAT*" | head -n1)

case $1 in
"--percentage")
  cat "$BAT_PATH/capacity" 2>/dev/null || echo "100"
  ;;
"--status")
  cat "$BAT_PATH/status" 2>/dev/null || echo "Full"
  ;;
"--present")
  [ -d "$BAT_PATH" ] && echo true || echo false
  ;;
esac
