#!/bin/bash

case $1 in
    "--usage")
        # Get CPU usage percentage
        top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print $1}'
        ;;
    "--temp")
        # Get CPU temperature
        sensors coretemp-isa-0000 | grep 'Package id 0:' | awk '{print $4}' | tr -d '+°C'
        ;;
    "--load")
        # Get CPU load average (1 minute)
        uptime | awk '{print $(NF-2)}' | sed 's/,//'
        ;;
esac

