] add speed 0.1
[ add speed -0.1
k cycle pause
j seek -10
l seek 10

WHEEL_LEFT ignore
WHEEL_RIGHT ignore

1 seek 10 absolute-percent
2 seek 20 absolute-percent
3 seek 30 absolute-percent
4 seek 40 absolute-percent
5 seek 50 absolute-percent
6 seek 60 absolute-percent
7 seek 70 absolute-percent
8 seek 80 absolute-percent
9 seek 90 absolute-percent
0 seek 0 absolute-percent

Ctrl+RIGHT add chapter 1
Ctrl+LEFT add chapter -1

c cycle sub-visibility
C cycle sub
a cycle audio

N playlist-next
P playlist-prev
