general {
    layout = dwindle

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour

    resize_on_border = true
}

dwindle {
  pseudotile = true # master switch for pseudotiling
	preserve_split = true
	smart_split = false
	smart_resizing = true
  force_split = 2 # 0 = split follows mouse, 1 = always split to the left, 2 = always split to the right
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    sync_gsettings_theme = true
    no_hardware_cursors = 2 # change to 1 if want to disable
    enable_hyprcursor = true
    warp_on_change_workspace = 2
    no_warps =false
}


xwayland {
  enabled = true
  force_zero_scaling = true
}

render {
  direct_scanout = 0
}

