input {
    numlock_by_default = false

    focus_on_close = 1

    kb_layout = gb
    follow_mouse = 1
    repeat_rate = 60
    repeat_delay = 300

    touchpad {
        natural_scroll = false
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
        tap-to-click = true
        tap-and-drag = true
        drag_lock = false
        middle_button_emulation = true
        clickfinger_behavior = false
    }
    tablet {
        transform = 0
        output = eDP-1
    }

    sensitivity = 0.1
    # force_no_accel = 1
    kb_options = caps:escape,lv3:ralt_alt # gb layout
}

