#!/bin/bash
case $1 in
    "--usage")
        # Get CPU usage percentage using psutil
        sar -u 1 1 | grep "Average" | awk '{print $3+$4+$5}'
        ;;
    "--temp")
        # Get CPU temperature
        sensors | awk '/Package id 0:/ {print $4; exit} /Tdie:/ {print $2; exit} /Tctl:/ {print $2; exit}' | tr -d '+°C'
        ;;
    "--load")
        # Get CPU load average (1 minute)
        uptime | awk '{print $(NF-2)}' | sed 's/,//'
        ;;
esac
