
source = $HOME/.config/hypr/configs/monitor.conf
source = $HOME/.config/hypr/configs/settings.conf
source = $HOME/.config/hypr/configs/env.conf
source = $HOME/.config/hypr/configs/startup.conf
source = $HOME/.config/hypr/configs/keybinds.conf
source = $HOME/.config/hypr/configs/decorations.conf
source = $HOME/.config/hypr/configs/zoom.conf
source = $HOME/.config/hypr/configs/window-rules.conf
source = $HOME/.config/hypr/configs/animations.conf
source = $HOME/.config/hypr/configs/workspaces.conf
source = $HOME/.config/hypr/configs/transparency.conf
source = $HOME/.config/hypr/configs/plugins.conf

