
general {
  resize_on_border = true
}

cursor {
  sync_gsettings_theme = true
  no_hardware_cursors = 2 # change to 1 if want to disable
  enable_hyprcursor = true
  warp_on_change_workspace = 2
  no_warps =false
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling
    preserve_split = true
    force_split = 2 # 0 = split follows mouse, 1 = always split to the left, 2 = always split to the right
    smart_split = false # Split in the direction that creates the most balanced container
}

input {
    kb_layout = gb
    follow_mouse = 1
    repeat_rate = 60
    repeat_delay = 300
    touchpad {
        natural_scroll = false
        disable_while_typing = true
        tap-to-click = true
        tap-and-drag = true
        drag_lock = false
        middle_button_emulation = true
        clickfinger_behavior = false
        scroll_factor = 1.0
    }
    tablet {
        transform = 0
        output = eDP-1
    }

    sensitivity = 0.1
    # force_no_accel = 1
    kb_options = caps:escape,lv3:ralt_alt # gb layout
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  vfr = true
  vrr = 2
  mouse_move_enables_dpms = true
  enable_swallow = off
  swallow_regex = ^(kitty)$
  focus_on_activate = false
  initial_workspace_tracking = 0
  middle_click_paste = false
}
#
# #opengl {
# #  nvidia_anti_flicker = true
# #}
#Could help when scaling and not pixelating
xwayland {
  enabled = true
  force_zero_scaling = true
}

render {
  direct_scanout = 0
}

