exec-once = eww daemon && eww open bar
exec-once = mullvad connect
exec-once = swww-daemon --format xrgb
exec-once = killall -q mako; swaync

$wall_dir = $HOME/Wallpapers
$swww_random = $HOME/.config/hypr/scripts/wallpaper/auto-refresh.sh

#exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

# wallpaper random
exec-once = $swww_random $wall_dir # random wallpaper switcher every 30 minutes

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit (Polkit Gnome / KDE)
exec-once = $HOME/.config/hypr/scripts/polkit.sh

# Starting hypridle to start hyprlock
exec-once = hypridle

exec-once = hyprctl dispatch workspace 2 && syncthing
exec-once = ghostty --gtk-single-instance=true --initial-window=false --quit-after-last-window-closed=false

# load plugins at startup. -n will make hyprpm send a notification if anything goes wrong (e.g. update needed)
exec-once = hyprpm reload -n
