windowrule = opacity 1.0, match:tag multimedia_video*
windowrule = opacity 1 0.85, match:tag browser*
windowrule = opacity 0.9 0.8, match:tag projects*
windowrule = opacity 0.94 0.86, match:tag im*
windowrule = opacity 0.94 0.86, match:tag multimedia*
windowrule = opacity 0.9 0.8, match:tag file-manager*
windowrule = opacity 1 0.92, match:tag terminal*
windowrule = opacity 0.8 0.7, match:tag settings*
windowrule = opacity 0.82 0.75, match:tag viewer*
windowrule = opacity 0.9 0.7, match:tag wallpaper*

windowrule = opacity 0.8 0.7, match:class ^(gedit|org\.gnome\.TextEditor|mousepad)$
windowrule = opacity 0.9 0.8, match:class ^(deluge|transmisson-qt)$
windowrule = opacity 0.9 0.8, match:class ^(im\.riot\.Riot)$ # Element Matrix client
windowrule = opacity 0.9 0.8, match:class ^(seahorse)$       # gnome-keyring GUI
windowrule = opacity 0.95 0.75, match:title ^(Picture-in-Picture)$

