$mainMod = SUPER
$terminal = ghostty --gtk-single-instance=true
$fileManager = thunar
$menu = rofi -lines 12 -padding 18 -width 60 -location 0 -show drun -sidebar-mode -columns 3 -font 'Noto Sans 8'

$gap_inner=5
$gap_outer=5
$gap_inner_special=5
$gap_outer_special=30
