source = $HOME/.config/hypr/configs/vars.conf
# pseudo-fullscreen
workspace = f[1], gapsout:0, gapsin:0, rounding:0

# Scratchpad system
# Define special workspaces for each number
workspace = special:s1, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s2, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s3, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s4, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s5, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s6, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s7, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s8, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s9, gapsout:$gap_outer_special, gapsin:$gap_inner_special
workspace = special:s0, gapsout:$gap_outer_special, gapsin:$gap_inner_special
