# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0C111B)
$foreground = rgb(B1B7C0)
$color0 = rgb(41362B)
$color1 = rgb(192539)
$color2 = rgb(1D2638)
$color3 = rgb(53352B)
$color4 = rgb(57362A)
$color5 = rgb(793075)
$color6 = rgb(AC7E4C)
$color7 = rgb(88909D)
$color8 = rgb(5F646E)
$color9 = rgb(21314C)
$color10 = rgb(26324B)
$color11 = rgb(6F4739)
$color12 = rgb(744838)
$color13 = rgb(A1409C)
$color14 = rgb(E5A865)
$color15 = rgb(88909D)
